name: Cross-OS Tests and Release

on:
  push:
    branches:
    - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-latest, macos-latest]
        node-version: [14, 16, 18]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test:ci

  release:
    name: Collect changes and Publish release
    runs-on: ubuntu-latest
    needs:
    - test
    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive
    - name: List changes
      run: ./scripts/write-release-message.sh
    - name: Create release and tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.1.${{ github.run_number }}
        release_name: Release v0.1.${{ github.run_number }}
        body_path: "changes.md"
        draft: false
        prerelease: false

  release-modules:
    name: Publish Modules
    runs-on: ubuntu-latest
    needs:
    - release
    strategy:
      matrix:
        submodule:
        - src/fi/hg/core
        - src/fi/hg/node
        - src/fi/hg/backend
        - src/fi/hg/frontend
        - src/fi/hg/matrix
        - src/fi/hg/ecb
        - src/fi/hg/ssr
        - src/fi/hg/repository
        - src/fi/hg/mysql
    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive
    - name: List changes
      run: ./scripts/write-release-message.sh
    - name: Move changes
      run: mv changes.md "${{ github.RUNNER_TEMP }}/changes.md"
    - name: Create release and tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.1.${{ github.run_number }}
        release_name: Release v0.1.${{ github.run_number }}
        body_path: "${{ github.RUNNER_TEMP }}/changes.md"
        draft: false
        prerelease: false
      working-directory: ${{ matrix.submodule }}
